### ISSUE TITLE
about set as_url get error

### ISSUE THREAD

**Issue by lcp0578** [Gregwar/CaptchaBundle#175]
hey, i'm set as_url = true,but i can't get the captcha?

app/config/config.yml

```
gregwar_captcha:
    expiration: 120
    width: 300
    height: 180
    length: 6
    as_url: true
    text_color: [255, 0, 255]
    background_color: [255, 255, 255]
    ignore_all_effects: false
    distortion: false
    interpolation: false
    charset: 'abcdefhjkmnprstuvwxyz'
```
it didn't work
![at9d8 n918g 9dpae5 x pt](https://user-images.githubusercontent.com/10859621/30853064-45ebee14-a2e0-11e7-998e-6ce009a82745.png)

so,i debug

```
class CaptchaController extends Controller
{
    /**
     * Action that is used to generate the captcha, save its code, and stream the image
     *
     * @param string $key
     *
     * @return Response
     *
     * @throws NotFoundHttpException
     */
    public function generateCaptchaAction($key)
    {
        $options = $this->container->getParameter('gregwar_captcha.config');
        $session = $this->get('session');
        $whitelistKey = $options['whitelist_key'];
        $isOk = false;
        dump($session->has($whitelistKey));
        if ($session->has($whitelistKey)) {
            $keys = $session->get($whitelistKey);
            dump($keys);
            if (is_array($keys) && in_array($key, $keys)) {
                $isOk = true;
            }
        }
        dump($isOk);die();
        if (!$isOk) {
            return $this->error($options);
        }
```
i got 
```
CaptchaController.php on line 31:
false
CaptchaController.php on line 39:
false
```
whitelist_key default value is 'captcha_whitelist_key'
get session value fail

where set the sesssion and how config keys
` $keys = $session->get($whitelistKey);`
in_array check?
thanks

**Comment by lcp0578** [comment]
@Gregwar can you help me?

**Comment by Gregwar** [comment]
It works without as_url ?
Your image suggest that there is a problem when drawing the text, maybe loading the font or generating the phrase

**Comment by Gregwar** [comment]
Actually, this is my bad, something broken BC in `gregwar/captcha`

Can you composer update and try again?

**Comment by lcp0578** [comment]
@Gregwar after composer it didn't work, in CaptchaController.php

```
public function generateCaptchaAction($key)
    {
        $options = $this->container->getParameter('gregwar_captcha.config');
        $session = $this->get('session');
        $whitelistKey = $options['whitelist_key'];
        $isOk = false;
        dump($session->has($whitelistKey));
        if ($session->has($whitelistKey)) {
            $keys = $session->get($whitelistKey);
            if (is_array($keys) && in_array($key, $keys)) {
                $isOk = true;
            }
        }
        dump($isOk);
        die();
        if (!$isOk) {
            return $this->error($options);
        }
```
output:
```
CaptchaController.php on line 31:
false
CaptchaController.php on line 38:
false
```
$isOk = false,so return $this->error(); i can't get the captcha?
whether my config error? 
I also can't get the code for set keys to session!

then,i force set $isOk = true
 ```
if ($session->has($whitelistKey)) {
            $keys = $session->get($whitelistKey);
            if (is_array($keys) && in_array($key, $keys)) {
                $isOk = true;
            }
        }
        $isOk = true;
        if (!$isOk) {
            return $this->error($options);
        }
```
the captcha in correct? 
how i config the white list key for security?
thanks

**Comment by lcp0578** [comment]
about set background_images:
```
gregwar_captcha:
    expiration: 120
    width: 300
    height: 180
    length: 6
    as_url: true
    text_color: [255, 0, 255]
    background_color: [255, 255, 255]
    ignore_all_effects: false
    distortion: true
    interpolation: true
    charset: 'abcdefhjkmnprstuvwxyz'
    background_images: ["%kernel.root_dir%/../web/static/images/captcha_bg.jpg", "%kernel.root_dir%/../web/static/images/captcha_bg.jpg"]
```
I got error.

```
ContextErrorException
--
Symfony\Component\Debug\Exception\ContextErrorException: Notice: Undefined variable: bg    at vendor\gregwar\captcha\CaptchaBuilder.php:461   at Gregwar\Captcha\CaptchaBuilder->build(300, 180, 'D:\\xampp\\htdocs\\kitlabs\\KitPHP\\vendor\\gregwar\\captcha-bundle\\DependencyInjection/../Generator/Font/captcha.ttf', null)      (vendor\gregwar\captcha-bundle\Generator\CaptchaGenerator.php:134)   at Gregwar\CaptchaBundle\Generator\CaptchaGenerator->generate(array('expiration' => 120, 'width' => 300, 'height' => 180, 'length' => 6, 'as_url' => true, 'text_color' => array(255, 0, 255), 'background_color' => array(255, 255, 255), 'ignore_all_effects' => false, 'distortion' => true, 'interpolation' => true, 'charset' => 'abcdefhjkmnprstuvwxyz', 'background_images' => array('D:\\xampp\\htdocs\\kitlabs\\KitPHP\\app/../web/static/images/captcha_bg.jpg', 'D:\\xampp\\htdocs\\kitlabs\\KitPHP\\app/../web/static/images/captcha_bg.jpg'), 'font' => 'D:\\xampp\\htdocs\\kitlabs\\KitPHP\\vendor\\gregwar\\captcha-bundle\\DependencyInjection/../Generator/Font/captcha.ttf', 'keep_value' => false, 'as_file' => false, 'reload' => false, 'image_folder' => 'captcha', 'web_path' => 'D:\\xampp\\htdocs\\kitlabs\\KitPHP\\app/../web', 'gc_freq' => 100, 'quality' => 30, 'invalid_message' => 'Bad code value', 'bypass_code' => null, 'whitelist_key' => 'captcha_whitelist_key', 'humanity' => 0, 'max_front_lines' => null, 'max_behind_lines' => null, 'disabled' => false, 'phrase' => 'tusnvk'))      (vendor\gregwar\captcha-bundle\Controller\CaptchaController.php:54)   at Gregwar\CaptchaBundle\Controller\CaptchaController->generateCaptchaAction('login')   at call_user_func_array(array(object(CaptchaController), 'generateCaptchaAction'), array('login'))      (vendor\symfony\symfony\src\Symfony\Component\HttpKernel\HttpKernel.php:153)   at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)      (vendor\symfony\symfony\src\Symfony\Component\HttpKernel\HttpKernel.php:68)   at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)      (vendor\symfony\symfony\src\Symfony\Component\HttpKernel\Kernel.php:171)   at Symfony\Component\HttpKernel\Kernel->handle(object(Request))      (web\app_dev.php:28)
```
thanks
