### ISSUE TITLE
How to test Captcha

### ISSUE THREAD

**Issue by engharb** [Gregwar/CaptchaBundle#193]
Hi,

I am running PhpUnit test but I do not know how to set the captcha value in the form before submitting the form?

May I can read the Symfony session but later the session will no longer valid/stored.

Any idea?

**Comment by Seb33300** [comment]
You should disable it in test environment.

``` yml
# config/packages/test/gregwar_captcha.yaml
gregwar_captcha:
    disabled: true
```
