### ISSUE TITLE
Symfony 5 support, documentation

### ISSUE THREAD

**Issue by tacman** [Gregwar/CaptchaBundle#207]
I'm having a hard time getting this bundle to work with Symfony 5.  

First, services.yml needs to have quotes around the parameter:

```yaml
services:
    # captcha type
    captcha.type:
        class: Gregwar\CaptchaBundle\Type\CaptchaType
        arguments: [ "@session", '%gregwar_captcha.config%' ]
        tags:
            - { name: form.type, alias: captcha }
```

But the issue I can't figure out is how to configure it.  I've tried adding things to my services.yaml file, but no luck.  

    gregwar_captcha:
        width: 200
        height: 50
        length: 6

OR

    gregwar_captcha: ~

How and where is the config defined for Symfony 5?
